# -*- coding: utf-8 -*-
"""EfficientNetB3_model_for_transfer_learning_and_object_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EXGbMm_GYtIIVV4DxKsPR1FUMQ-3Hewi
"""

! pip install -q kaggle
!pip install h5py

from google.colab import files
files.upload()

! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
! kaggle datasets list

!kaggle datasets download -d sadmansakibmahi/class-of-leaf
#!kaggle datasets download -d emmarex/plantdisease
#!kaggle datasets download -d sadmansakibmahi/plant-disease-expert

!unzip /content/class-of-leaf.zip
#!!unzip /content/plant-disease-expert.zip
#!unzip /content/plantdisease.zip

import numpy as np
import pandas as pd
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import time
import matplotlib.pyplot as plt
import cv2
import seaborn as sns
sns.set_style('darkgrid')
import shutil
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense, Activation,Dropout,Conv2D, MaxPooling2D,BatchNormalization
from tensorflow.keras.optimizers import Adam, Adamax
from tensorflow.keras.metrics import categorical_crossentropy
from tensorflow.keras import regularizers
from tensorflow.keras.models import Model
import time

dataset_path = "/content/Dataset/Dataset"
!pip install efficientnet

"""**Section 1: Dataset Overview**

This section analyzes a dataset by counting the number of images in each class. It creates a DataFrame with two columns: "Plant Class" and "Number of Images." The data is then sorted based on the number of images, and a horizontal bar chart is plotted to visualize the distribution of images across different plant classes. The top 5 classes with the minimum number of images are printed.

**Section 2: Dataset Preparation**

This section prepares the dataset for machine learning. It sets a minimum threshold (min_samples) for the number of images a class must have to be included. It creates a DataFrame (df) containing file paths and corresponding labels. The dataset is then split into training, validation, and test sets using the train_test_split function. The script prints the lengths of these sets and the number of classes in the training set.

**Section 3: Dataset Statistics**

This section computes and prints statistics about the training dataset, such as the number of images per class. It also identifies classes with the maximum and minimum number of training images. Additionally, it calculates the average height, width, and aspect ratio of a sample of images from the training set.

In summary, these sections collectively provide insights into the dataset's composition, prepare the dataset for training, and offer statistical information useful for understanding the data characteristics before building a machine learning model.
"""

directory = dataset_path

total_number = 0
total_classes = 0
name_classes = []
len_classes = []

for folder in os.listdir(directory):
    folder_path = os.path.join(directory, folder)
    if os.path.isdir(folder_path):
        num_files = len(os.listdir(folder_path))
        len_classes.append(num_files)
        name_classes.append(folder)
        total_number += num_files
        total_classes += 1

data = {'Plant Class': name_classes, 'Number of Images': len_classes}

df = pd.DataFrame(data)
df_sorted = df.sort_values('Number of Images')

plt.figure(figsize=(20, 15))
plt.barh(df_sorted['Plant Class'], df_sorted['Number of Images'])
plt.title('Overview of the Dataset')
plt.xlabel('Number of Data')
plt.ylabel('Plant Classes')
plt.show()
print("//////////////////////////////")
min_classes = df_sorted.head(5)
print(min_classes[['Plant Class', 'Number of Images']])



print("//////////////////////////////")

sdir=(dataset_path)
min_samples=40 # set limit for minimum images a class must have to be included in the dataframe
filepaths = []
labels=[]
classlist=os.listdir(sdir)
for klass in classlist:
    classpath=os.path.join(sdir, klass)
    flist=os.listdir(classpath)
    if len(flist) >= min_samples:
        for f in flist:
            fpath=os.path.join(classpath,f)
            filepaths.append(fpath)
            labels.append(klass)
    else:
        print('class ', klass, ' has only', len(flist), ' samples and will not be included in dataframe')
Fseries=pd.Series(filepaths, name='filepaths')
Lseries=pd.Series(labels, name='labels')
df=pd.concat([Fseries, Lseries], axis=1)
train_df, dummy_df=train_test_split(df, train_size=.9, shuffle=True, random_state=123, stratify=df['labels'])
valid_df, test_df=train_test_split(dummy_df, train_size=.5, shuffle=True, random_state=123, stratify=dummy_df['labels'])
print('train_df lenght: ', len(train_df), '  test_df length: ', len(test_df), '  valid_df length: ', len(valid_df))
# get the number of classes and the images count for each class in train_df
classes=sorted(list(train_df['labels'].unique()))
class_count = len(classes)
print('The number of classes in the dataset is: ', class_count)
groups=train_df.groupby('labels')
print('{0:^30s} {1:^13s}'.format('CLASS', 'IMAGE COUNT'))
countlist=[]
classlist=[]
for label in sorted(list(train_df['labels'].unique())):
    group=groups.get_group(label)
    countlist.append(len(group))
    classlist.append(label)
    print('{0:^30s} {1:^13s}'.format(label, str(len(group))))

# get the classes with the minimum and maximum number of train images
max_value=np.max(countlist)
max_index=countlist.index(max_value)
max_class=classlist[max_index]
min_value=np.min(countlist)
min_index=countlist.index(min_value)
min_class=classlist[min_index]
print(max_class, ' has the most images= ',max_value, ' ', min_class, ' has the least images= ', min_value)
# lets get the average height and width of a sample of the train images
ht=0
wt=0
# select 100 random samples of train_df
train_df_sample=train_df.sample(n=100, random_state=123,axis=0)
for i in range (len(train_df_sample)):
    fpath=train_df_sample['filepaths'].iloc[i]
    img=plt.imread(fpath)
    shape=img.shape
    ht += shape[0]
    wt += shape[1]
print('average height= ', ht//100, ' average width= ', wt//100, 'aspect ratio= ', ht/wt)

"""# trim Function Explanation:

The trim function is designed to adjust the dataset by limiting the number of samples per class. Here's a step-by-step breakdown:

**Input Parameters:**

df: The input DataFrame containing file paths and labels.
        max_samples: The maximum number of samples allowed per class.
        min_samples: The minimum number of samples required for a class to be included.
        column: The column in the DataFrame representing class labels.

 **Grouping by Class:**

The function groups the DataFrame (df) by the specified column (column), which typically represents class labels.

**Trimming Process:**

For each unique label (class), the function checks the number of samples in that class.
        If the count is greater than max_samples, it randomly samples max_samples instances from that class, creating a subset.
        If the count is between min_samples and max_samples (inclusive), it includes all samples from that class without any trimming.
        If the count is less than min_samples, the class is excluded from the trimmed dataset.

**Result:**

The trimmed subsets for each class are concatenated into a new DataFrame (trimmed_df).
        The function prints a message indicating the maximum and minimum samples per class after trimming.

 **Output:**
        The function returns the trimmed DataFrame, which now adheres to the specified limits on the number of samples per class.
"""

def trim(df, max_samples, min_samples, column):
    df=df.copy()
    groups=df.groupby(column)
    trimmed_df = pd.DataFrame(columns = df.columns)
    groups=df.groupby(column)
    for label in df[column].unique():
        group=groups.get_group(label)
        count=len(group)
        if count > max_samples:
            sampled_group=group.sample(n=max_samples, random_state=123,axis=0)
            trimmed_df=pd.concat([trimmed_df, sampled_group], axis=0)
        else:
            if count>=min_samples:
                sampled_group=group
                trimmed_df=pd.concat([trimmed_df, sampled_group], axis=0)
    print('after trimming, the maximum samples in any class is now ',max_samples, ' and the minimum samples in any class is ', min_samples)
    return trimmed_df

max_samples= 198855 # since each class has more than 198855 images all classes will be trimmed to have 50000 images per class
min_samples=36
column='labels'
train_df= trim(train_df, max_samples, min_samples, column)

"""# Data Generators Setup Explanation:

**Parameters Setup:**

batch_size: The number of samples per batch during training.
        trgen: An image data generator for training with various augmentations like horizontal flip, rotation, and shifts.
        t_and_v_gen: An image data generator for validation and testing without additional augmentations.

**Training Data Generator:**

train_gen: Flow generator created from the training DataFrame (train_df).
        Images are loaded from file paths (x_col='filepaths') with corresponding labels (y_col='labels').
        Target image size is set to (200, 200), and the color mode is RGB.
        The generator is set to shuffle the data (shuffle=True) and to yield batches of size batch_size.

**Validation Data Generator:**

valid_gen: Flow generator for validation data with similar parameters to the training generator, except shuffle is set to False.

**Test Data Generator:**

test_gen: Flow generator for test data.
        The script dynamically calculates the batch size and test steps to ensure that all samples in the test set are processed exactly once.
        The generator is set to not shuffle the data (shuffle=False) to facilitate later analysis.

**Information Extraction:**

Lists of class names (classes) and their corresponding indices (class_indices) are extracted from the training generator.
        The number of classes is determined (class_count).
        The labels from the test generator are stored in the labels variable.

**Print Statements:**

Display information about the test batch size, test steps, and the number of classes.
        Print the total number of images in the training, validation, and test sets.

In summary, this script prepares data generators for efficient loading and augmentation of images during training and evaluation, ensuring compatibility with the specified image dimensions and batch sizes.

"""

batch_size=20 # We will use and EfficientetB3 model, with image size of (200, 250) this size should not cause resource error
trgen=ImageDataGenerator(horizontal_flip=True,rotation_range=20, width_shift_range=.2,
                                  height_shift_range=.2, zoom_range=.2 )
t_and_v_gen=ImageDataGenerator()
msg='{0:70s} for train generator'.format(' ')
print(msg, '\r', end='') # prints over on the same line
train_gen=trgen.flow_from_dataframe(train_df, x_col='filepaths', y_col='labels', target_size=(200, 250),
                                   class_mode='categorical', color_mode='rgb', shuffle=True, batch_size=batch_size)
msg='{0:70s} for valid generator'.format(' ')
print(msg, '\r', end='') # prints over on the same line
valid_gen=t_and_v_gen.flow_from_dataframe(valid_df, x_col='filepaths', y_col='labels', target_size= (200, 250),
                                   class_mode='categorical', color_mode='rgb', shuffle=False, batch_size=batch_size)
# for the test_gen we want to calculate the batch size and test steps such that batch_size X test_steps= number of samples in test set
# this insures that we go through all the sample in the test set exactly once.
length=len(test_df)
test_batch_size=sorted([int(length/n) for n in range(1,length+1) if length % n ==0 and length/n<=80],reverse=True)[0]
test_steps=int(length/test_batch_size)
msg='{0:70s} for test generator'.format(' ')
print(msg, '\r', end='') # prints over on the same line
test_gen=t_and_v_gen.flow_from_dataframe(test_df, x_col='filepaths', y_col='labels', target_size= (200, 250),
                                   class_mode='categorical', color_mode='rgb', shuffle=False, batch_size=test_batch_size)
# from the generator we can get information we will need later
classes=list(train_gen.class_indices.keys())
class_indices=list(train_gen.class_indices.values())
class_count=len(classes)
labels=test_gen.labels
print ( 'test batch size: ' ,test_batch_size, '  test steps: ', test_steps, ' number of classes : ', class_count)


print("Total Train Image:-",len(train_df))
print("Total Validation Image:-",len(valid_df))
print("Total Test Image:-",len(test_df))

def show_image_samples(gen ):
    t_dict=gen.class_indices
    classes=list(t_dict.keys())
    images,labels=next(gen) # get a sample batch from the generator
    plt.figure(figsize=(20, 20))
    length=len(labels)
    if length<25:   #show maximum of 25 images
        r=length
    else:
        r=25
    for i in range(r):
        plt.subplot(5, 5, i + 1)
        image=images[i] /255
        plt.imshow(image)
        index=np.argmax(labels[i])
        class_name=classes[index]
        plt.title(class_name, color='black', fontsize=11)
        plt.axis('off')
    plt.show()

show_image_samples(train_gen)

"""# **EfficientNetB3  model for Transfer learning**
The input shape for the images is set to (300, 300, 3), representing height, width, and channels. The dataset is then divided into training and testing sets using the train_test_split function, with stratification based on the 'labels' column to maintain class distribution.

EfficientNetB3, a pre-trained convolutional neural network architecture, is imported and instantiated with weights pre-loaded from ImageNet. To preserve the pre-trained weights, all layers of the base model are frozen.

The model is constructed by adding additional layers on top of the EfficientNetB3 base. It includes a Global Average Pooling layer, a dense layer with ReLU activation, a dropout layer to prevent overfitting, and a final dense layer with softmax activation for multi-class classification.

The model is then compiled using the Adam optimizer with a specified learning rate, categorical crossentropy as the loss function, and accuracy as the evaluation metric.

For effective data handling, data generators (train_gen and test_gen) are created using ImageDataGenerator from Keras. These generators facilitate real-time data augmentation during training and ensure proper data flow to the model during testing. Augmentation techniques include rescaling, horizontal flipping, rotation, and shifting.

The flow_from_dataframe method is employed to configure the data flow from Pandas DataFrames (train_df and test_df) to the model. This involves specifying file paths, labels, target size, and batch size. Additionally, one-hot encoding is applied to class labels during training.

Overall, this script provides a well-organized and modularized approach to building an image classification model. It leverages the transfer learning capabilities of EfficientNetB3 and incorporates essential practices such as data splitting, model compilation, and data augmentation for robust training.
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam
from efficientnet.tfkeras import EfficientNetB3  # Import EfficientNetB3

# Assuming df contains the file paths and labels
# Adjust the input shape based on the requirements of EfficientNetB3
input_shape = (300, 300, 3)

# Split the dataset into training and testing sets
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['labels'])

# Create an instance of the EfficientNetB3 model pre-trained on ImageNet data
base_model = EfficientNetB3(weights='imagenet', include_top=False, input_shape=input_shape)

# Freeze the layers of the pre-trained model
for layer in base_model.layers:
    layer.trainable = False

# Build your model on top of the EfficientNetB3 base
num_classes = len(train_df['labels'].unique())
model = keras.Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Create data generators
batch_size = 32
trgen = ImageDataGenerator(rescale=1./255, horizontal_flip=True, rotation_range=20, width_shift_range=0.2, height_shift_range=0.2, zoom_range=0.2)
tgen = ImageDataGenerator(rescale=1./255)

train_gen = trgen.flow_from_dataframe(dataframe=train_df, directory=None,
                                      x_col='filepaths', y_col='labels',
                                      target_size=(input_shape[0], input_shape[1]),
                                      class_mode='categorical',
                                      batch_size=batch_size)

test_gen = tgen.flow_from_dataframe(dataframe=test_df, directory=None,
                                    x_col='filepaths', y_col='labels',
                                    target_size=(input_shape[0], input_shape[1]),
                                    class_mode='categorical',
                                    batch_size=batch_size,
                                    shuffle=False)

"""# **Train the model**"""

# Train the model
epochs = 6  # Adjust the number of epochs as needed
history = model.fit(train_gen,
                    steps_per_epoch=train_gen.samples // batch_size,
                    epochs=epochs,
                    validation_data=test_gen,
                    validation_steps=test_gen.samples // batch_size)

"""# **Additional Training or model re_Training**"""

# Additional Training
additional_epochs = 10  # Adjust the number of additional epochs as needed
history_additional = model.fit(train_gen,
                               steps_per_epoch=train_gen.samples // batch_size,
                               epochs=additional_epochs,
                               validation_data=test_gen,
                               validation_steps=test_gen.samples // batch_size)

"""# **Evaluate the model on the test set**"""

# Evaluate the model on the test set
test_results = model.evaluate(test_gen, steps=test_gen.samples // batch_size)
print("\nTest Set Evaluation:")
print("Test Loss:", test_results[0])
print("Test Accuracy:", test_results[1])

class_indices
classlist

"""# **Generate predictions**"""

# Generate predictions
predictions = model.predict(test_gen, steps=test_gen.samples // batch_size)
predicted_labels = np.argmax(predictions, axis=1)
true_labels = test_gen.classes

def tr_plot(tr_data, start_epoch):
    #Plot the training and validation data
    tacc=tr_data.history['accuracy']
    tloss=tr_data.history['loss']
    vacc=tr_data.history['val_accuracy']
    vloss=tr_data.history['val_loss']
    Epoch_count=len(tacc)+ start_epoch
    Epochs=[]
    for i in range (start_epoch ,Epoch_count):
        Epochs.append(i+1)
    index_loss=np.argmin(vloss)#  this is the epoch with the lowest validation loss
    val_lowest=vloss[index_loss]
    index_acc=np.argmax(vacc)
    acc_highest=vacc[index_acc]
    plt.style.use('fivethirtyeight')
    sc_label='best epoch= '+ str(index_loss+1 +start_epoch)
    vc_label='best epoch= '+ str(index_acc + 1+ start_epoch)
    fig,axes=plt.subplots(nrows=1, ncols=2, figsize=(20,8))
    axes[0].plot(Epochs,tloss, 'r', label='Training loss')
    axes[0].plot(Epochs,vloss,'g',label='Validation loss' )
    axes[0].scatter(index_loss+1 +start_epoch,val_lowest, s=150, c= 'blue', label=sc_label)
    axes[0].set_title('Training and Validation Loss')
    axes[0].set_xlabel('Epochs')
    axes[0].set_ylabel('Loss')
    axes[0].legend()
    axes[1].plot (Epochs,tacc,'r',label= 'Training Accuracy')
    axes[1].plot (Epochs,vacc,'g',label= 'Validation Accuracy')
    axes[1].scatter(index_acc+1 +start_epoch,acc_highest, s=150, c= 'blue', label=vc_label)
    axes[1].set_title('Training and Validation Accuracy')
    axes[1].set_xlabel('Epochs')
    axes[1].set_ylabel('Accuracy')
    axes[1].legend()
    plt.tight_layout
    plt.show()

tr_plot(history,0)

def re_training_plot(tr_data, start_epoch):
    # Plot the training and validation data
    tacc = tr_data.history['accuracy']
    tloss = tr_data.history['loss']
    vacc = tr_data.history['val_accuracy']
    vloss = tr_data.history['val_loss']
    Epoch_count = len(tacc) + start_epoch
    Epochs = [i + 1 for i in range(start_epoch, Epoch_count)]
    index_loss = np.argmin(vloss)  # epoch with the lowest validation loss
    val_lowest = vloss[index_loss]
    index_acc = np.argmax(vacc)
    acc_highest = vacc[index_acc]

    plt.style.use('fivethirtyeight')
    sc_label = 'best epoch= ' + str(index_loss + 1 + start_epoch)
    vc_label = 'best epoch= ' + str(index_acc + 1 + start_epoch)

    fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(20, 8))

    # Plotting Training and Validation Loss
    axes[0].plot(Epochs, tloss, 'r', label='Re_Training loss')
    axes[0].plot(Epochs, vloss, 'g', label='Re_Validation loss')
    axes[0].scatter(index_loss + 1 + start_epoch, val_lowest, s=150, c='blue', label=sc_label)
    axes[0].set_title('Training and Validation Loss')
    axes[0].set_xlabel('Epochs')
    axes[0].set_ylabel('Loss')
    axes[0].legend()

    # Plotting Training and Validation Accuracy
    axes[1].plot(Epochs, tacc, 'r', label='Re_Training Accuracy')
    axes[1].plot(Epochs, vacc, 'g', label='Re_Validation Accuracy')
    axes[1].scatter(index_acc + 1 + start_epoch, acc_highest, s=150, c='blue', label=vc_label)
    axes[1].set_title('Training and Validation Accuracy')
    axes[1].set_xlabel('Epochs')
    axes[1].set_ylabel('Accuracy')
    axes[1].legend()

    plt.tight_layout()
    plt.show()

# Plot the initial training history
re_training_plot(history_additional, 0)

# Plot the additional training history
#re_training_plot(history_additional, len(history.history['accuracy']))

"""# **Save the model**"""

subject='model'
save_id= subject+ '.h5'
model_save_loc = save_id
model.save(model_save_loc)
print ('model was saved as ' , model_save_loc )

from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
import numpy as np

def load_and_preprocess_image(image_path):
    img = image.load_img(image_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0  # Normalize the pixel values to be between 0 and 1
    return img_array

def classify_image(model, image_path, class_labels):
    img_array = load_and_preprocess_image(image_path)
    predictions = model.predict(img_array)
    predicted_class_index = np.argmax(predictions)
    predicted_class = class_labels[predicted_class_index]
    confidence = predictions[0][predicted_class_index]

    return predicted_class, confidence

if __name__ == "__main__":
    # Load the saved model
    model_path = "/content/model.h5"
    loaded_model = load_model(model_path)

    # Define your class labels
    class_labels =['Pepper__bell___Bacterial_spot',
 'Pepper__bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Tomato_Bacterial_spot',
 'Tomato_Early_blight',
 'Tomato_Late_blight',
 'Tomato_Leaf_Mold',
 'Tomato_Septoria_leaf_spot',
 'Tomato_Spider_mites_Two_spotted_spider_mite',
 'Tomato__Target_Spot',
 'Tomato__Tomato_YellowLeaf__Curl_Virus',
 'Tomato__Tomato_mosaic_virus',
 'Tomato_healthy'] # Replace with your actual class labels

    # Provide the path to the image you want to classify
    image_path = "/content/PlantVillage/Pepper__bell___Bacterial_spot/0022d6b7-d47c-4ee2-ae9a-392a53f48647___JR_B.Spot 8964.JPG"

    # Perform image classification
    predicted_class, confidence = classify_image(loaded_model, image_path, class_labels)

    # Print the results
    print(f"Predicted Class: {predicted_class}")
    print(f"Confidence: {confidence}")

"""# **Model Quantization**"""

Model_path = "/content/model.h5"
import tensorflow as tf
model = tf.keras.models.load_model(Model_path)

"""**Optimize.DEFAULT Quantization**"""

import tensorflow as tf
model = tf.keras.models.load_model(Model_path)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
tf_lite_Optimize_DEFAULT_model = converter.convert()
print("Optimize.DEFAULT Quantization:- ",len(tf_lite_Optimize_DEFAULT_model))

"""**OPTIMIZE_FOR_SIZE Quantization**"""

import tensorflow as tf
model = tf.keras.models.load_model(Model_path)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.target_spec.supported_types = [tf.float16]
OPTIMIZE_FOR_SIZE_model = converter.convert()
print("OPTIMIZE_FOR_SIZE Quantization [tf.float16]:- ",len(OPTIMIZE_FOR_SIZE_model))

"""**OPTIMIZE_FOR_LATENCY Quantization**"""

import tensorflow as tf
model = tf.keras.models.load_model(Model_path)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_LATENCY]
converter.target_spec.supported_types = [tf.float16]
OPTIMIZE_FOR_LATENCY_model = converter.convert()
print("OPTIMIZE_FOR_LATENCY Quantization:- ",len(OPTIMIZE_FOR_LATENCY_model))

with open("OPTIMIZE_FOR_SIZE_model.tflite", "wb") as f:
    f.write(OPTIMIZE_FOR_SIZE_model)

# save the DEFAULT Quantization model in HDF5 format
with open("tf_lite_Optimize_DEFAULT_model.tflite", "wb") as f:
    f.write(tf_lite_Optimize_DEFAULT_model)

# save the OPTIMIZE_FOR_LATENCY_model in HDF5 format
with open("OPTIMIZE_FOR_LATENCY_model.tflite", "wb") as f:
    f.write(OPTIMIZE_FOR_LATENCY_model)

import numpy as np
from PIL import Image
import tensorflow as tf

def load_and_preprocess_image(image_path, target_size=(224, 224)):
    img = Image.open(image_path)
    img = img.resize(target_size)
    img_array = np.array(img, dtype=np.float32) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

def classify_image_tflite(interpreter, image_path, class_labels):
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    img_array = load_and_preprocess_image(image_path, target_size=(input_details[0]['shape'][1], input_details[0]['shape'][2]))

    interpreter.set_tensor(input_details[0]['index'], img_array)
    interpreter.invoke()

    predictions = interpreter.get_tensor(output_details[0]['index'])
    predicted_class_index = np.argmax(predictions)
    predicted_class = class_labels[predicted_class_index]
    confidence = predictions[0][predicted_class_index]

    return predicted_class, confidence

if __name__ == "__main__":
    # Load the TFLite model
    model_path_tflite = "/content/OPTIMIZE_FOR_SIZE_model.tflite"
    interpreter = tf.lite.Interpreter(model_path=model_path_tflite)
    interpreter.allocate_tensors()

    # Define your class labels
    class_labels = ['Pepper__bell___Bacterial_spot',
 'Pepper__bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Tomato_Bacterial_spot',
 'Tomato_Early_blight',
 'Tomato_Late_blight',
 'Tomato_Leaf_Mold',
 'Tomato_Septoria_leaf_spot',
 'Tomato_Spider_mites_Two_spotted_spider_mite',
 'Tomato__Target_Spot',
 'Tomato__Tomato_YellowLeaf__Curl_Virus',
 'Tomato__Tomato_mosaic_virus',
 'Tomato_healthy']  # Replace with your actual class labels

    # Provide the path to the image you want to classify
    image_path = "/content/PlantVillage/Pepper__bell___Bacterial_spot/0022d6b7-d47c-4ee2-ae9a-392a53f48647___JR_B.Spot 8964.JPG"

    # Perform image classification using TFLite model
    predicted_class, confidence = classify_image_tflite(interpreter, image_path, class_labels)

    # Print the results
    print(f"Predicted Class: {predicted_class}")
    print(f"Confidence: {str(str(100*(confidence)))}")